name: civic_flutter
description: A new Flutter project with Serverpod.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.10.7

dependencies:
  animated_text_kit:
  cached_network_image:
  carousel_slider: ^5.1.1
  civic_client:
    path: ../civic_client
  cupertino_icons: ^1.0.5
  dio: ^5.7.0
  dropdown_button2: ^2.3.9
  expandable_richtext: ^1.0.7
  expandable_text:
  file_picker: ^10.3.8
  firebase_core: ^4.4.0
  firebase_messaging: ^16.0.3
  flex_color_scheme: ^8.2.0
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.4.1
  flutter_dotenv: ^6.0.0
  flutter_map: ^8.0.0
  flutter_native_splash: ^2.4.5
  flutter_quill: ^11.4.2
  flutter_quill_extensions: ^11.0.0
  flutter_riverpod: ^3.0.1
  flutter_staggered_grid_view: ^0.7.0
  font_awesome_flutter:
  fpdart: ^1.0.0
  geolocator:
  go_router:
  google_fonts:
  iconsax:
  image_cropper:
  image_gallery_saver_plus: ^4.0.1
  image_picker:
  infinite_scroll_pagination: ^5.1.1
  intl: ^0.20.2
  latlong2: ^0.9.1
  loading_animation_widget:
  meta: any
  path: ^1.9.0
  path_provider:
  permission_handler:
  pinput:
  responsive_framework: ^0.2.0
  riverpod_annotation: ^4.0.0
  serverpod_auth_client: 3.2.3
  serverpod_auth_email_flutter: 3.2.3
  serverpod_auth_shared_flutter: 3.2.3
  serverpod_flutter: 3.2.3
  shared_preferences:
  smooth_page_indicator:
  timeago: ^3.7.1
  toastification:
  transparent_image:
  url_launcher:
  video_player:
  visibility_detector: ^0.4.0

dev_dependencies:
  build_runner: ^2.6.0
  custom_lint:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  riverpod_generator: ^4.0.0+1
  riverpod_lint: ^3.0.1
  very_good_analysis: ^10.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/logo/
    - assets/env/
  
  fonts:
    - family: Jakarta
      fonts:
        - asset: assets/fonts/PlusJakartaSans-Bold.otf
          weight: 700
        - asset: assets/fonts/PlusJakartaSans-ExtraBold.otf
          weight: 800
        - asset: assets/fonts/PlusJakartaSans-Medium.otf
          weight: 500
        - asset: assets/fonts/PlusJakartaSans-Regular.otf
          weight: 400
        - asset: assets/fonts/PlusJakartaSans-SemiBold.otf
          weight: 600       
        - asset: assets/fonts/PlusJakartaSans-Light.otf
          weight: 300
        - asset: assets/fonts/PlusJakartaSans-ExtraLight.otf
          weight: 200