name: civic_server
description: Starting point for a Serverpod server.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  dio: ^5.7.0
  serverpod: 3.1.1
  serverpod_auth_server: 3.1.1
  serverpod_cloud_storage_s3: 3.1.1
  serverpod_serialization: 3.1.1
  mailer: ^6.6.0
  dotenv: ^4.2.0
  googleapis_auth: ^2.0.0

dev_dependencies:
  lints: ">=3.0.0 <5.0.0"
